### ISSUE TITLE
Prometheus not scraping traefik

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/faf-stack#141]
As Traefik runs in network mode host, it's not available as alias on the docker network.

To make it available for prometheus we can use `extra_hosts` with docker_host pointing to the HOST_IP which is to be added in the env file.
Also then point to docker_host in the default prometheus configuration

**Comment by p4block** [comment]
We acknowledge that it is a small hack but it seems to be how others also do it. If a newer docker version allows for something else, we'll switch.
