### ISSUE TITLE
Create a backup script for the database

### ISSUE THREAD

**Issue by yaniv-aknin** [FAForever/faf-stack#217]
Right now we export the mariadb as sql file. That crashed on import with a "table full" error and also takes ages. It would be probably be easier to use ZFS snapshots and cold backups.

We'd need to either pause the database (with [`BACKUP STAGE`](https://mariadb.com/kb/en/backup-stage/)) or treat the snapshot as a crashed database and recover it before backing up.

We should also decide between `zfs send` as our backup mechanism or temporary read-only mounting of the snapshot and creating a tarball of database files.

The resulting data should be zstd compressed and dumped to NFS.

**Comment by Brutus5000** [comment]
Solved in #218
