### ISSUE TITLE
IPv6 issues

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-stack#25]
Not all services work properly for people with IPv6.

* https://faforever.com/ works
* https://api.faforever.com/ works
* http://content.faforever.com/ does not work (connection refused)
* https://forums.faforever.com/ works, but it uses Cloudflare (so no direct connection is made)
* IPv6 addresses get replaced with the container-internal IPv4 address (e.g. in `login.ip`)

This issue will be updated as I gather more information

**Comment by Brutus5000** [comment]
Not sure if there are any problems caused and this is 5 years old.

**Comment by p4block** [comment]
It's still an issue, docker is just a tech dead end. It will actually get fixed with the migration to k8s (that very recently introduced support)

**Comment by micheljung** [comment]
Docker is a tech dead end? What?

We could either use network mode `host` or https://github.com/robbertkl/docker-ipv6nat

**Comment by Brutus5000** [comment]
We used network mode `host` for the reverse proxy and I saw several ipv6 addresses for http request. Not sure about the  tcp protocols though. 
And docker engine itself is getting deprecated slowly. It got replaced in with containerd and/or other solutions in many places such as Kubernetes.
