### ISSUE TITLE
Fix faf-clans.env

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-stack#6]
See https://github.com/FAForever/faf-stack/pull/2/files#r118688142

**Comment by IDragonfire** [comment]
Not idea how I can fix this, all variables are required for oauth an local developments...

**Comment by IDragonfire** [comment]
Why is this a bug?

**Comment by IDragonfire** [comment]
Like this ? https://github.com/FAForever/faf-stack/pull/7

**Comment by Brutus5000** [comment]
Superseeded by #112
